config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    resources :vehicels do
      resources :locations do
      end
    end
  end


  resources :home do
      collection do
        get :about
        get :hdwconnection
      end
  end

  namespace :api do
    resources :pings, only: :index, constraints: { format: 'json' }
    resources :locations, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :vehicel
  belongs_to :user
  validates :latitude , uniqueness: true
  validates :longitude , uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vehicels, :dependent => :destroy
  has_many :locations, :dependent => :destroy
end

app/models/vehicel.rb
class Vehicel < ApplicationRecord
  belongs_to :user
  has_many :locations, :dependent => :destroy
  validates :First_name, presence:true, length: {minimum:3, maximum:50}
  validates :surname, presence:true, length: {minimum:3, maximum:50}
  validates :vehicel_brand, presence:true, length: {minimum:3, maximum:50}
  validates :vehicel_model, presence:true, length: {minimum:3, maximum:50}
  validates :vehicel_color, presence:true, length: {minimum:3, maximum:50}
  validates :plate_number,uniqueness:true , presence:true, length: {minimum:3, maximum:50}
end

app/controllers/api/locations_controller.rb
module Api
  class LocationsController < ApiController

    def index
      locations = Location.all
      render json: locations, status: :ok
    end

    def create

      location = Location.create!(location_params)
      render json: location, status: :ok if location.save
    end

    private

    def location_params
      params.permit(:latitude, :longitude, :user_id, :vehicel_id)
    end
  end
end

app/controllers/api/pings_controller.rb
module Api
  class PingsController < ApiController

    def index
      render json: { response: 'pong' }
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :about]


  def index
  end

  def about
  end

  def hdwconnection
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
   skip_before_action :authenticate_user!, only: [:create]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.where("user_id = ?", params[:user_id])
    return @locations = Location.where("vehicel_id = ? ", params[:search_field]).all if params[:commit] == "Search"
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
     @location = Location.create(latitude: params[:latitude], longitude: params[:longitude], user_id: params[:user_id],vehicel_id: params[:vehicel_id])
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location}
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create


  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location}
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to user_vehicel_locations_path(params[:user_id],params[:vehicel_id])}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :user_id, :vehicel_id)
    end
end

app/controllers/vehicels_controller.rb
class VehicelsController < ApplicationController
  before_action :set_user,only: [:new,:edit,:update,:show,:destroy,:create]
  before_action :set_vehicel, only: [:show, :edit, :update, :destroy]

  # GET /vehicels
  # GET /vehicels.json
  def index
    @vehicels = Vehicel.where("user_id = ?", params[:user_id]).order(created_at: :desc)
    return @vehicels = Vehicel.where("vehicel_brand like ? or vehicel_model like ?", "%#{params[:search_field].downcase}%" , "%#{params[:search_field].downcase}%").all if params[:commit] == "Search"
  end
  # GET /vehicels/1
  # GET /vehicels/1.json
  def show
    @vehicel = @user.vehicels.find(params[:id])
  end

  # GET /vehicels/new
  def new
   
   @vehicel = @user.vehicels.build
  end

  # GET /vehicels/1/edit
  def edit
  end

  # POST /vehicels
  # POST /vehicels.json
  def create

    @vehicel = @user.vehicels.create(vehicel_params)
    respond_to do |format|
      if @vehicel.save
        format.html { redirect_to user_vehicels_path(@user, @vehicel) }
        format.json { render :show, status: :created, location: @vehicel }
      else
        format.html { render :new }
        format.json { render json: @vehicel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicels/1
  # PATCH/PUT /vehicels/1.json
  def update
    @vehicel = @user.vehicels.find(params[:id])
    respond_to do |format|
      if @vehicel.update(vehicel_params)
        format.html { redirect_to user_vehicels_path(@user), notice: 'Vehicel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicel }
      else
        format.html { render :edit }
        format.json { render json: @vehicel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicels/1
  # DELETE /vehicels/1.json
  def destroy
    @vehicel =  @user.vehicels.find(params[:id])
    @vehicel.destroy
    respond_to do |format|
      format.html { redirect_to user_vehicels_path(@user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicel
      @vehicel = Vehicel.find(params[:id])
    end

    def set_user
    @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicel_params
      params.require(:vehicel).permit(:First_name, :surname, :vehicel_brand, :vehicel_model, :vehicel_color, :plate_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def errors_for(object)
    if object.errors.any?
        content_tag(:div, class: "card border-danger") do
            concat(content_tag(:div, class: "card-header bg-danger text-white") do
                concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
            end)
            concat(content_tag(:div, class: "card-body") do
                concat(content_tag(:ul, class: 'mb-0') do
                    object.errors.full_messages.each do |msg|
                        concat content_tag(:li, msg)
                    end
                end)
            end)
        end
    end
end
end

app/views/home/about.html.erb
<div class="container bg-white about-wh">
  <h2 class="about-heading">How to track your Vehicle?</h2>
    <div class = "about-text">
      <p class="text-left">
       VTS (Vehicle Tracking System) is a system that allow you to konw the location of your Vehicle. In order to track your Vehicle you have to follow the following steps:


    <ul class="list-group list-group-flush text-left">
      <li class="list-group-item">1- You have to obtain our vts hardware device (info on how to obtain the device please contact: +27611557995 or muandatito@gmail).<br/><br/>
      <%= image_tag 'hdwimg1', width: '400px', hight: '400px' %>
      </li>

      <li class="list-group-item">2- Open an account on this website.</li>
      <li class="list-group-item">3 - Register your vehicle on this website.</li>
      <li class="list-group-item">4- After completing steps 2 and 3 will be provided with a user id and vehicle id use both to register your vts hardware device.</li>
    </ul>


    <h2 class="about-heading " >How to setup my vts hardware device?
    </h2>
    <ul class="list-group list-group-flush text-left">
      <li class= "list-group-item">1 -Open the vts hardware box</li>
      <li class= "list-group-item">2 -Provind a SIM car to the SIM socket<br/><br/>
        <%= image_tag 'hdwimg2', width:'400px', hight:'400px' %>
        <blockquote class="blockquote">
          <p class="text-size text-muted">Note: Make sure your sim card is working and it does not contain a security pin, and also it must contain internet data and sms data.</p>
        </blockquote>
      </li>
       <li class= "list-group-item">3 -Close the vts box and you good to go :)</li>
       <br/><br/>
    </ul>
  </div>
</div>

app/views/home/hdwconnection.html.erb
<p id="hardware_state">
hello world
<p>

app/views/home/index.html.erb
<header class="v-header container">
  <div class="fullscreen-video-wraper">
    <%= video_tag "map.mkv", controls: false, autoplay: true, muted: true, loop: true%>
  </div>

  <div class="header-overlay"></div>
  <div class="header-content">
    <span class="text-header">
      <h1 class="text-header-main text-light">know your vehicle location</h1>
      <%= link_to 'track your vehicle', about_home_index_path, class: 'btn btn-success link-upper btn-lg text-light' %>
    </span>
  </div>

</header>

app/views/layouts/_flash_message.html.erb
<div class ="container-flash">
<div class="row row-padding">
    <div class="col-xs-10 col-xs-offset-1 full-width">
    <% flash.each do |key, value| %>
      <div role="alert" class=" alert-dismissible fade show alert alert-<%= key %>"><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>

      </div>
      <% end %>
    </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small  pt-8 bg-dark">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-center">

      <!-- Grid row -->


          <!-- Content -->
          <h5 class="text-light h4">Food-up</h5>
          <small class='text-size'>FoodUp is an application that allow you to share your culcute through gastronomy
          share your Recipe Food or Drink, let other know :)
          </small>


        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">
          </div>
          <!-- Grid column -->


    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3   bg-copyright">© 2018 Copyright:
      CraftByts
    </div>
    <!-- Copyright -->

  </footer>

app/views/layouts/_navmenu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-black z-index">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
        <a class="navbar-brand d-none d-lg-inline-block text-light logo-text" href="/home">
            Vehicle Tracking System <i class="material-icons">time_to_leave</i><i class="material-icons icon-scale text-warning">location_on</i>
        </a>
        <a class="navbar-brand-two mx-auto d-lg-none d-inline-block" href="#">
           <i class="material-icons text-white" style = "font-size: 3.5rem">time_to_leave</i>
        </a>
        <div class="w-100 text-right">
            <button class="navbar-toggler bg-danger " type="button" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggler-icon "></span>
            </button>
        </div>
    </div>
    <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
        <ul class="navbar-nav ml-auto flex-nowrap">
            <li class="nav-item">
                 <%= link_to "Home", home_index_path,:class=>"nav-link m-2 menu-item active text-warning" %>
            </li>
            <% if user_signed_in?%>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light drop-menu" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%>
                <div class="dropdown-menu">
                 <%= link_to "Register Your Vehicle",  new_user_vehicel_path(current_user),:class=>"dropdown-item first-drop-item no-display" %>
                 <%= link_to "Vehicle location",   user_vehicels_path(current_user),:class=>"dropdown-item" %>
                 <%= link_to "Edit Accout",  edit_user_registration_path,:class=>"dropdown-item" %>

                 <%= link_to "Vehicle location history",  user_vehicel_locations_path(current_user, 1),:class=>"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete,:class=>"dropdown-item" %>
                </div>
              </li>
            <%else%>
              <li class="nav-item">
              <%= link_to "Login",  new_user_session_path,:class=>"nav-link m-2 menu-item text-light" %>
            </li>
            <li class="nav-item">
                 <%= link_to "Sign-Up", new_user_registration_path,:class=>"nav-link m-2 menu-item text-light" %>
            </li>
            <%end%>
              <li class="nav-item">
                   <%= link_to "about Us", about_home_index_path,:class=>"nav-link m-2 menu-item text-light" %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VehicelTrackingSystem</title>
        <script type='text/javascript'
            src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap' 
            async defer></script>
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
      <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navmenu' %>

    <p class="alert"><%= notice %></p>
    <p class="alert"><%= alert %></p>
   



    <%= yield %>



  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, value: @latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, value: @longitude %>
  </div>



  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, value: @user_id  %>
  </div>

  <div class="field">
    <%= form.label :vehicel_id %>
    <%= form.number_field :vehicel_id, value: @vehicel_id  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%= link_to user_vehicel_locations_path(current_user), :class=>"link" do %>
      <h1 class="signin-text form-text-spacing btn-margin">Locations History</h1>
  <%end%>


 <%= form_tag( user_vehicel_locations_path(current_user), method: "get", class: 'form-inline search-form') do %>
      <%= text_field_tag :search_field,"", class: 'form-control mr-sm-2 search-inout', placeholder: 'Search using vehicle ID' %>
      <%= submit_tag "Search",class:"btn btn-outline-success my-2 my-sm-0" %>
 <%end%>



<table class="table">
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Vehicel ID</th>
      <th>Date</th>
      <th>Address</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.vehicel_id %></td>
        <td><%= location.created_at %></td>
        <td><%= link_to 'view', "http://maps.google.com/maps?q=loc:#{location.latitude},#{location.longitude}" %></td>
        <td><%= link_to '<i class="material-icons text-danger">delete</i>'.html_safe, user_vehicel_location_path(current_user, location.vehicel_id,location.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @location.user_id %>
</p>

<p>
  <strong>Vehicel:</strong>
  <%= @location.vehicel_id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/vehicels/_editForm.html.erb
<%= form_with(model: vehicel, local: true,  url: user_vehicel_path(current_user, @vehicel), method: :put) do |form| %>
  <% if vehicel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicel.errors.count, "error") %> prohibited this vehicel from being saved:</h2>

      <ul>
      <% vehicel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :First_name,:class=>"form-text-spacing" %>
    <%= form.text_field :First_name,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :surname,:class=>"form-text-spacing" %>
    <%= form.text_field :surname,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_brand,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_brand,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_model,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_model,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_color,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_color,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :plate_number,:class=>"form-text-spacing" %>
    <%= form.text_field :plate_number,:class=> "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit 'register your vehicel',:class=>"btn btn-primary btn-margin form-text-spacing" %>
  </div>
<% end %>

app/views/vehicels/_form.html.erb
<%= form_with(model: vehicel, local: true,  url: user_vehicels_path(current_user)) do |form| %>
  <% if vehicel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicel.errors.count, "error") %> prohibited this vehicel from being saved:</h2>

      <ul>
      <% vehicel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :First_name,:class=>"form-text-spacing" %>
    <%= form.text_field :First_name ,:class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :surname,:class=>"form-text-spacing" %>
    <%= form.text_field :surname,:class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_brand,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_brand,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_model,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_model,:class=> "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :vehicel_color,:class=>"form-text-spacing" %>
    <%= form.text_field :vehicel_color,:class=> "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :plate_number, :class=>"form-text-spacing" %>
    <%= form.text_field :plate_number,:class=> "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit 'register your vehicle', :class=>"btn btn-primary btn-margin form-text-spacing" %>
  </div>
<% end %>

app/views/vehicels/edit.html.erb
<div class="container login-text">
  <h1 class="text">Editing Vehicel info</h1>

  <%= render 'editForm', vehicel: @vehicel %>

  <%= link_to 'Show', user_vehicel_path(current_user,@vehicel) %> |
  <%= link_to 'Back', user_vehicels_path(current_user)  %>
</div>

app/views/vehicels/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container login-text with-container">
  <%= link_to user_vehicels_path(current_user), :class=>"link" do %>
      <h1 class="signin-text form-text-spacing btn-margin text">Vehicle List</h1>
  <%end%>


 <%= form_tag( user_vehicels_path(current_user), method: "get", class: 'form-inline search-form') do %>
      <%= text_field_tag :search_field,"", class: 'form-control mr-sm-2 search-inout', placeholder: 'Search using vehicle brand or model' %>
      <%= submit_tag "Search",class:"btn btn-outline-success my-2 my-sm-0" %>
 <%end%>

  <table class="table">
    <thead>
      <tr>
        <th>First name</th>
        <th>Surname</th>
        <th>Vehicel brand</th>
        <th>Vehicel model</th>
        <th>Vehicel color</th>
        <th>Plate number</th>
        <th>User ID</th>
        <th>Vehicle ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicels.each do |vehicel| %>
        <tr>
          <td><%= vehicel.First_name %></td>
          <td><%= vehicel.surname %></td>
          <td><%= vehicel.vehicel_brand %></td>
          <td><%= vehicel.vehicel_model %></td>
          <td><%= vehicel.vehicel_color %></td>
          <td><%= vehicel.plate_number %></td>
          <td><%= vehicel.user_id %></td>
          <td><%= vehicel.id %></td>
          <td><%= link_to 'Show', user_vehicel_path(current_user, vehicel.id),'data-no-turbolink':  true %></td>
          <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_user_vehicel_path(current_user, vehicel.id) %></td>
          <td><%= link_to '<i class="material-icons text-danger">delete</i>'.html_safe, user_vehicel_path(current_user, vehicel.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Vehicel', new_user_vehicel_path(current_user),:class=>"btn btn-primary form-text-spacing btn-margin" %>
</div>

app/views/vehicels/new.html.erb
<div class="container login-text ">
  <h1 class="text">Register your vehicle</h1>


  <%= render 'form', vehicel: @vehicel ,url: user_vehicels_path(current_user)%>

  <%= link_to 'Back', user_vehicels_path %>
</div>

app/views/vehicels/show.html.erb
 <div id="myMap"></div>



<script type='text/javascript'>
    let defaultColor = 'purple',
        hoverColor = 'blue',
        user_lat, user_long,
        mouseDownColor = 'red',
        map, searchManager,
        lat_  = 0.0,
        long_ = 0.0;

     <% @vehicel.locations.each do |l|%>
        lat_ = parseFloat('<%= l.latitude%>')
        long_ = parseFloat('<%= l.longitude%>')
     <%end%>

       function GetMap() {
        map = new Microsoft.Maps.Map('#myMap', {
            credentials: 'AjX11KcC0K8DVPhGhcq6w_4x4on1ZL8i0XRjz9Skdt_MVZ90kxw7JQcxyxnSFFf5 ',
            center: new Microsoft.Maps.Location(lat_, long_),
            zoom: 15
        });
        //Make a request to reverse geocode the center of the map.
        reverseGeocode();
    }

    function reverseGeocode() {
        //If search manager is not defined, load the search module.
        if (!searchManager) {
            //Create an instance of the search manager and call the reverseGeocode function again.
            Microsoft.Maps.loadModule('Microsoft.Maps.Search', () => {
                searchManager = new Microsoft.Maps.Search.SearchManager(map);
                reverseGeocode();
            });
        } else {
            let searchRequest = {
                location: map.getCenter(),
                callback: (r) => {
                    //Tell the user the name of the result.

                const center = map.getCenter();
                const pin = new Microsoft.Maps.Pushpin(center, {
                title: 'Vehicle location',
                subTitle: r.name,
                text: 'V'
                 });

        //Add the pushpin to the map
        map.entities.push(pin);
         Microsoft.Maps.Events.addHandler(pin, 'mouseover',(e) => {
            e.target.setOptions({ color: hoverColor });
        });

        Microsoft.Maps.Events.addHandler(pin, 'mousedown', (e) => {
            e.target.setOptions({ color: mouseDownColor });
        });

        Microsoft.Maps.Events.addHandler(pin, 'mouseout', (e) => {
            e.target.setOptions({ color: defaultColor });
        });
                },
                errorCallback: function (e) {
                    //If there is an error, alert the user about it.
                    alert("Unable to reverse geocode location.");
                }
            };

            //Make the reverse geocode request.
            searchManager.reverseGeocode(searchRequest);
        }
    }

      $(document).on('ready turbolinks:change turbolinks:load', () => {


   GetMap();

      });

    </script>

    <%= link_to 'Edit', edit_user_vehicel_path(current_user,@vehicel), :class=> 'btn btn-outline-success btn-map' %>
    <%= link_to 'Back', user_vehicels_path(current_user), :class=> 'btn btn-outline-success btn-map' %>